ci(major-release): support run major release [0-9]+.0.0
fix

update docs

fix

fix

diff --git a/.github/workflows/prepare-release/action.yml b/.github/workflows/prepare-release/action.yml
--- a/.github/workflows/prepare-release/action.yml
+++ b/.github/workflows/prepare-release/action.yml
@@ -49,6 +49,14 @@ runs:
         VERSION: ${{ inputs.version }}
       shell: 'bash'
 
+    - name: validate version format (major only)
+      if: ${{ inputs.type == 'major' && ! endsWith(inputs.version, '0.0') }}
+      run: |-
+        FAILURE_MESSAGE='version is not a major one but a patch (only support for <major>.0.0)'
+        echo "FAILURE_MESSAGE=${FAILURE_MESSAGE}" >> "$GITHUB_ENV"
+        echo "::error::${FAILURE_MESSAGE}" ; exit 1
+      shell: 'bash'
+
     - name: validate version format (minor only)
       if: ${{ inputs.type == 'minor' && ! endsWith(inputs.version, '0') }}
       run: |-
@@ -64,6 +72,18 @@ runs:
         echo "FAILURE_MESSAGE=${FAILURE_MESSAGE}" >> "$GITHUB_ENV"
         echo "::error::${FAILURE_MESSAGE}" ; exit 1
       shell: 'bash'
+
+    - name: validate if branch already exists (minor only)
+      if: ${{ inputs.type == 'major' }}
+      run: |-
+        if git ls-remote --exit-code --heads https://github.com/${{ github.repository }}.git "$BRANCH" > /dev/null ; then
+          FAILURE_MESSAGE='Branch already exists. This is not a major release.'
+          echo "FAILURE_MESSAGE=${FAILURE_MESSAGE}" >> "$GITHUB_ENV"
+          echo "::error::${FAILURE_MESSAGE}" ; exit 1
+        fi
+      shell: 'bash'
+      env:
+        BRANCH: ${{ steps.generate.outputs.release-branch }}
 
     - name: validate if branch already exists (minor only)
       if: ${{ inputs.type == 'minor' }}
