[8.18](backport #16278) Revert "disable validate-wolfi-docker-image workflow" (#16367)
* Revert "disable validate-wolfi-docker-image workflow (#16222)" (#16278)

This reverts commit 163acaea8ff4357b07002b8dd5439d02dd334853.

(cherry picked from commit abe10464f043b024f2e29e0ff0b2c92140666f22)

# Conflicts:
#	.github/workflows/ci.yml

* Update ci.yml

---------

Co-authored-by: Victor Martinez <victormartinezrubio@gmail.com>
Co-authored-by: kruskall <99559985+kruskall@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -129,24 +129,24 @@ jobs:
 
   # Only for forked PRs, when changing the .go-version, then we need to note that the wolfi docker image needs to be
   # validated
-  #validate-wolfi-docker-image:
-  #  runs-on: ubuntu-latest
-  #  if: ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true ) || github.actor == 'dependabot[bot]'
-  #  steps:
-  #    - uses: actions/checkout@v4
-  #    - name: Get changed files
-  #      id: changed-files
-  #      uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45.0.6
-  #      with:
-  #        files: .go-version
-  #
-  #    - name: If .go-version changed validate docker image is available.
-  #      if: steps.changed-files.outputs.any_changed == 'true'
-  #      run: |
-  #        echo "If you change the .go-version please use a branch in the upstream repository to validate the wolfi images with test-package-and-push."
-  #        echo "Otherwise, this validation will run and fail the CI build."
-  #        echo "Please validate the wolfi image is available by running the following command:"
-  #        echo "::notice::docker pull docker.elastic.co/wolfi/go:$(cat .go-version)"
-  #        echo "If they are available you could skip this validation."
-  #        echo "However, we recommend to use an upstream branch to run the CI specialised steps for the packaging system."
-  #        exit 1
+  validate-wolfi-docker-image:
+    runs-on: ubuntu-latest
+    if: ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true ) || github.actor == 'dependabot[bot]'
+    steps:
+      - uses: actions/checkout@v4
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
+        with:
+          files: .go-version
+
+      - name: If .go-version changed validate docker image is available.
+        if: steps.changed-files.outputs.any_changed == 'true'
+        run: |
+          echo "If you change the .go-version please use a branch in the upstream repository to validate the wolfi images with test-package-and-push."
+          echo "Otherwise, this validation will run and fail the CI build."
+          echo "Please validate the wolfi image is available by running the following command:"
+          echo "::notice::docker pull docker.elastic.co/wolfi/go:$(cat .go-version)"
+          echo "If they are available you could skip this validation."
+          echo "However, we recommend to use an upstream branch to run the CI specialised steps for the packaging system."
+          exit 1
