report non supported versions

diff --git a/.github/workflows/run-minor-release.yml b/.github/workflows/run-minor-release.yml
--- a/.github/workflows/run-minor-release.yml
+++ b/.github/workflows/run-minor-release.yml
@@ -26,6 +26,10 @@ jobs:
         run: |-
           echo "release-branch=${VERSION%.*}" >> "${GITHUB_OUTPUT}"
           echo "release-version=${VERSION}" >> "${GITHUB_OUTPUT}"
+          if [[ ! $VERSION =~ [0-9]+\.[0-9]+\.0 ]]; then
+            echo "::error::version is not a minor one but a patch: (only support <major>.<minor>.0)"
+            exit 1
+          fi
         env:
           VERSION: ${{ inputs.version }}
 
diff --git a/.github/workflows/run-patch-release.yml b/.github/workflows/run-patch-release.yml
--- a/.github/workflows/run-patch-release.yml
+++ b/.github/workflows/run-patch-release.yml
@@ -22,9 +22,15 @@ jobs:
       release-version: ${{ steps.generate.outputs.release-version }}
     steps:
       - id: generate
-        run: echo "release-version=${VERSION}" >> "${GITHUB_OUTPUT}"
+        run: |-
+          echo "release-version=${VERSION}" >> "${GITHUB_OUTPUT}"
+          if [[ $VERSION =~ [0-9]+\.[0-9]+\.0 ]]; then
+            echo "::error::version is not a patch one but a minor: (only support for <major>.<minor>.[1-9]+[0-9]*)"
+            exit 1
+          fi
         env:
           VERSION: ${{ inputs.version }}
+
   run-patch:
     runs-on: ubuntu-latest
     needs: [ prepare ]
